### PR TITLE
feat: split min/max size constraints

### LINKED ISSUE #138: Feature Request: Constrain window width, but not window height.
See discussion including screenshots at Discord.

https://discord.com/channels/616186924390023171/625037620996734986/866688857139314729

"setting maxWidth breaks the vertical resizing" ... "also enforces the minHeight as its maxHeight"

My project need to be able to keep approximately the same width, but adjust height during runtime. E.g. like Apple Music for macOS does. It can be resized horizontally, but only up to a maxWidth. However height can be as high as you'd like.

### PR DESCRIPTION
**Pull request by amrbashir**
closes #138

### What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### Checklist
- [X] This PR will resolve #___
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary
- [X] It can be built on all targets and pass CI/CD.

### CODE REVIEW

**Comment by amrbashir** [comment]
macOS testers needed here

**Comment by pewsheen** [comment]
> macOS testers needed here

It works well on macOS 🎉

**Comment by amrbashir** [comment]
A few cleanup using macros from https://github.com/rust-windowing/winit/pull/2148, I've already tested Windows and Linux but would love to get second eyes and approvals here:
- @pewsheen macos 
- @FabianLars linux
- @simonhyll windows

**Comment by pewsheen** [comment]
> A few cleanup using macros from [rust-windowing/winit#2148](https://github.com/rust-windowing/winit/pull/2148), I've already tested Windows and Linux but would love to get second eyes and approvals here:
> 
> * @pewsheen macos
> * @FabianLars linux
> * @simonhyll windows

macOS is fine 👍

**Comment by FabianLars** [comment]
So far tested on fedora38+gnome, wsl (ubuntu2204), and windows. Any specific DEs or distros you want me to test?

**Comment by amrbashir** [comment]
Not really, these are enough, thanks

**Comment by amrbashir** [comment]
Alright, this should be read for approval.

**Review by FabianLars — APPROVED** [review]
(only skimmed over the macros part since i'm not really into that stuff, but the rest looks solid to me)

**Comment by amrbashir** [comment]
alright, I will ping @wusyong to take a look before I merge

**Review by wusyong — APPROVED** [review]

**Pull request merged**
