### PR TITLE
feat(macos): add `SystemTray::set_tooltip` , ref #409

### LINKED ISSUE #409: [feat] tray add set_tool_tip method
It would be nice to set the tool tip on the tray icon. Electron has this feature here: https://www.electronjs.org/docs/latest/api/tray/#traysettooltiptooltip .

### PR DESCRIPTION
**Pull request by pevers**
### What kind of change does this PR introduce?
This implements the `set_tool_tip` method on a tray. I understand that this will probably not be merged before the v1 release. Please let me know if I can continue to work on this to also support the other platforms or if you would rather wait.

Screenshot 2022-05-29 at 18 15 10

This should close https://github.com/tauri-apps/tao/issues/409

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by pevers** [comment]
Hi, sorry to bother @wusyong , is it ok to continue work on this?

**Comment by amrbashir** [comment]
@pevers sorry for the delay. It would be perfect if you can finish Linux and Windows implementation but if you don't want too I can merge this and add them later.

**Comment by pevers** [comment]
> @pevers sorry for the delay. It would be perfect if you can finish other Linux and Windows implementation but if you don't want too I can merge this and add them later.

Thanks for your reply @amrbashir ! I currently don't have access to my Windows machine, so I updated this PR and I can create an issue for the Windows and Linux implementation if that is OK?

**Comment by amrbashir** [comment]
It is fine, I will add them in this PR tomorrow or later today.

**Comment by amrbashir** [comment]
Sorry for the delay, I totally forgot I was going to implement other platforms.

It seems Linux's libappindicator doesn't support setting tooltips so I refactored the PR a bit for future Windows implementation because I can't do it right now.

**Review by amrbashir — APPROVED** [review]
Thanks

**Pull request merged**
