### PR TITLE
refactor(linux): remove zbus and use unity launcher APIs directly

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

**Comment by amrbashir** [comment]
I have wasted so much time today trying to see if this implementation works but I can't confirm that it works at all, I couldn't also get the zbus implementation to work as well.

**Review by lucasfernog — APPROVED** [review]

**Comment by zeenix** [comment]
> I have wasted so much time today trying to see if this implementation works but I can't confirm that it works at all,

This also adds more code and hence complexity but if maintainers are happy, why not? :)

> I couldn't also get the zbus implementation to work as well.

In the future, if you have problems using zbus, do consider asking for help, either in our [issues](https://github.com/dbus2/zbus/issues), [discussions](https://github.com/dbus2/zbus/discussions) or [our Matrix channel](https://matrix.to/#/#zbus:matrix.org).

**Comment by amrbashir** [comment]
@zeenix thank you, it wasn't an issue with zbus itself at all. I simply wasn't able to observe the effects of the implementation on the window manager.

As for the decision to remove zbus, was because it added a bit of size (around 500kb) to the minimalist tauri app. We still use zbus in other places like single-instance and notifications (through notify-rust) plugins but that's optional additions.

**Comment by zeenix** [comment]
> @zeenix thank you, it wasn't an issue with zbus itself at all. I simply wasn't able to observe the effects of the implementation on the window manager.

Ah ok.

> As for the decision to remove zbus, was because it added a bit of size (around 500kb) to the minimalist tauri app.

Fair enough. I'm working on some changes slowly that should help with the size issue.

> We still use zbus in other places like single-instance and notifications (through notify-rust) plugins but that's optional additions.

:+1:

**Pull request merged**
