### PR TITLE
Added instructions for Fedora in the README.

### PR DESCRIPTION
**Pull request by blemelin**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [X] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [X] No

### Checklist
- [X] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary

### Other information

Added a section in the `README.md` file about the required dependencies on Fedora. One less Google search to do I guess.

### CODE REVIEW

**Comment by blemelin** [comment]
Oups. Merged the wrong thing in my branch. Don't merge this.

**Comment by FabianLars** [comment]
(@team) We may wanna hijack this PR and update the other distros to use ayatana instead.

**Comment by wusyong** [comment]
@FabianLars yeah you can pushed commits if needed. But I'm not familiar with Fedora. Not sure how's their libappindicator situation.

**Comment by FabianLars** [comment]
> Not sure how's their libappindicator situation.

It's bad lol. They are the only one who seemingly don't want to commit to ayatana. There's not even a usable copr repo (think of AUR for fedora)...
But **the PR is correct for fedora**. What i thought is that we may want to change the recommendation for ubuntu to `libayatana-appindicator3-dev` since it's now the default in tao. No idea how the package is called on arch btw (or if it's available as in AUR only).

We may want to leave it as-is so that it's consistent for now. The package names are mentioned in the `Cargo features` section anyway.

**Comment by lucasfernog** [comment]
In Arch it's only available in the AUR: https://aur.archlinux.org/packages/libayatana-appindicator

**Pull request closed without merging**
