### PR TITLE
Remove trivial tray features

### PR DESCRIPTION
**Pull request by wusyong**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by wusyong** [comment]
@FabianLars @lucasfernog Do you agree on this? If so, I want to publish this as soon as possible.

**Comment by FabianLars** [comment]
Fine by me 👍 

What do you think about removing the tray feature from the default features?

**Comment by wusyong** [comment]
Sure, I think it's also more reasonable.

**Comment by lucasfernog** [comment]
Seems good, we can deal with it at Tauri.

**Comment by nazar-pc** [comment]
I traced `ayatana` removal to here, why did it happen?
I can't build it on Ubuntu 22.04 anymore because I have `libayatana-appindicator` instead of `libappindicator` installed.

Before this PR `ayatana-tray` was the default feature, now it is not possible to use at all, I'm confused why this PR is a "feature" and not a major breaking change.

**Pull request merged**
