### PR TITLE
refactor(macos): run set focus on main thread

### LINKED ISSUE #129: feat: Better `set_focus` handling
Right now on macOS we had to disable the `is_visible` check as it's async.
On Windows and Linux it works fine.

Maybe we should do a cleanup in this.

You can test with this examples;
```rust
use simple_logger::SimpleLogger;
use tao::{
  accelerator::{Accelerator, SysMods},
  event::{Event, WindowEvent},
  event_loop::{ControlFlow, EventLoop},
  keyboard::KeyCode,
  platform::global_shortcut::ShortcutManager,
  window::WindowBuilder,
};

#[allow(clippy::single_match)]
fn main() {
  let event_loop = EventLoop::new();

  let window = WindowBuilder::new()
    .with_title("A fantastic window!")
    .with_inner_size(tao::dpi::LogicalSize::new(128.0, 128.0))
    .build(&event_loop)
    .unwrap();

  let shortcut_1 = Accelerator::new(SysMods::Shift, KeyCode::KeyB);
  let mut hotkey_manager = ShortcutManager::new(&event_loop);
  hotkey_manager.register(shortcut_1.clone()).unwrap();

  event_loop.run(move |event, _, control_flow| {
    *control_flow = ControlFlow::Wait;
    match event {
      Event::GlobalShortcutEvent(hotkey_id) if hotkey_id == shortcut_1.clone().id() => {
        if window.is_visible() {
          println!("Making invisible");
          window.set_visible(false);
        } else {
          println!("Making Visible and Focused");
          window.set_visible(true);
          window.set_focus();
        }
      }
      Event::WindowEvent {
        event: WindowEvent::CloseRequested,
        window_id,
        ..
      } if window_id == window.id() => *control_flow = ControlFlow::Exit,
      Event::MainEventsCleared => {
        window.request_redraw();
      }
      _ => (),
    }
  });
}
```

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### Checklist
- [x] This PR will resolve #129
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary
- [X] It can be built on all targets and pass CI/CD.

### CODE REVIEW

**Comment by amrbashir** [comment]
this is porting some of the changes in winit, namely this commit https://github.com/rust-windowing/winit/commit/bf92f3e97b997293e3c621021ed4a4a99233ab91 and as always, I need macOS testers to test this PR

**Comment by pewsheen** [comment]
I have yet to test it all. So far, the window will hang when I toggle fullscreen or maximize. Changing these two functions back to `Queue::main().exec_async` work normally.

It hangs while calling
```rs
ns_window.toggleFullScreen_(nil);
```

**Comment by amrbashir** [comment]
Does it hang on winit too? if so we should report it but for now I will revert for these two functions, let me know if others behave similarily.

**Comment by pewsheen** [comment]
> Does it hang on winit too? if so we should report it but for now I will revert for these two functions, let me know if others behave similarily.

It looks like they were keeping these two functions async and making it sync in the commit https://github.com/rust-windowing/winit/commit/2e4d79f57a9cdc3124e78d3fabc4da3daea7748c

Though they changed `restore_display_mode_async` to sync in their latter commit, I didn't find it stuck in this PR.

And actually, the code was stuck on acquiring `shared_state`'s mutex lock at https://github.com/tauri-apps/tao/blob/6df56c2dd1b0f4695dd40b70f75a22d1ba32c384/src/platform_impl/macos/window_delegate.rs#L533-L551

**Comment by amrbashir** [comment]
alright, I will just revert these changes and keep the relevant ones for the issue to be closed

**Comment by amrbashir** [comment]
@pewsheen could you see if this PR doesn't reintroduce the bug mentioned in #129?

**Comment by pewsheen** [comment]
I'm using the example in #129, and here are some test results between branches and tag points:

- tao-v0.3.1: Not Focused when visible
- dev: Focused when visible
- this PR: Focused when visible

**Comment by amrbashir** [comment]
thanks

**Review by wusyong — APPROVED** [review]

**Pull request merged**
