### PR TITLE
fix: scale cursor_position

### LINKED ISSUE #708: `window.cursor_position()` is actually `LogicalPosition`
**Describe the bug**
`Window.cursor_position()` returns a `PhysicalPosition` which has to be multiplied by the scale factor to get the same value as the `CursorMoved` event.  Thus `Window.cursor_position()` is a different value from `CursorMoved` if scaling is in use.

This occurs at least on Hyprland on linux.

`CursorMoved` explicitly handles the conversion to PhysicalPosition [here](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/linux/event_loop.rs#L580).

**Steps to reproduce**
I don't have a MWE but could probably get one together.  This was discovered in EmacsNG (too large to compile just to reproduce).  Credit to @declantsien for working out what the problem was.

**Expected behavior**
Positions should be identical.

**Platform and Versions (please complete the following information):**
OS: Linux 6.2.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:23 +0000 x86_64 GNU/Linux
Rustc: rustc 1.69.0-nightly (7aa413d59 2023-02-19)

**Would you want to assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Additional context**
I don't know if this occurs on other platforms. Windows makes an [os call](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/windows/util.rs#L235-L244) as does [Mac](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/macos/util/mod.rs#L127-L132).  But linux goes via 
the [gdk Display](https://github.com/tauri-apps/tao/blob/28b53f80c49bbf2ae8902b98a2e28f6451a5a8f1/src/platform_impl/macos/util/mod.rs#L127-L132).  I'm guessing the seat returns a scaled position as I can't find anything in the gdk docs.

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Checklist
- [X] This PR will resolve #708
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tao/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary
- [X] It can be built on all targets and pass CI/CD.

### CODE REVIEW

**Comment by amrbashir** [comment]
@wusyong I fixed the linux impl, feel free to take macOS. Windows should be working fine iirc but I will test later today once I switch back to windows.

**Comment by wusyong** [comment]
@amrbashir I tested with `event_loop.cursor_position()` and it'll return error.
And I feel like this is tricky when two monitors have different scale factors. Not sure if this could be the case.

Edit: Linux should be easier because I believe it's all one display one screen now. They should share same scale factor.

**Comment by amrbashir** [comment]
> I tested with `event_loop.cursor_position()` and it'll return error.

I haven't been able to get it to error at all, using one screen or two.

> And I feel like this is tricky when two monitors have different scale factors. Not sure if this could be the case.
> Edit: Linux should be easier because I believe it's all one display one screen now. They should share same scale factor.

yeah they share the same scale_factor at least on my KDE.

**Comment by amrbashir** [comment]
just tested Windows and it works as expected with single and multi-monitor setup

**Comment by wusyong** [comment]
macOS added

**Comment by amrbashir** [comment]
can't approve my own PR so feel free to approve and merge

**Comment by wusyong** [comment]
but where's Windows?

**Comment by amrbashir** [comment]
Windows works fine

**Comment by amrbashir** [comment]
Tested it yesterday

**Review by wusyong — APPROVED** [review]
I also tested on Windows myself and you are right.

**Pull request merged**
