### PR TITLE
[WIP] fix #63: Add SystemTray::set_icon to change the icon at runtime

### LINKED ISSUE #63: Update `tray` menu items
We should have the option to rebuild the tray menu after the app is launched.

- [x] Windows
- [x] macOS
- [x] Linux

### PR DESCRIPTION
**Pull request by fnune**
Draft PR to solve https://github.com/tauri-apps/tao/issues/64

- [x] Linux
- [ ] Windows
- [ ] macOS

Submitting this early since I have the feeling that I'm making the code
a lot uglier. I'm new to Rust in terms of actual contributions so I'd
like a first pass review to see if I'm approaching this the right way.

I decided to add an `instance` field to `SystemTray` so that it can hold
the platform-specific system tray instance, in the case of Linux that's
an `AppIndicator`. This is so that later on we can access that instance
during runtime and use its `set_icon` method.

Later on this can be extended to `set_items` to also solve https://github.com/tauri-apps/tao/issues/63

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No (I think? I now take `&mut self` in `SystemTray::initialize`)

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by fnune** [comment]
Just looking for initial feedback. It's my first PR, so I'm sure existing maintainers will go "hell no" with some of my code.

**Comment by fnune** [comment]
The changes seem reasonably transferable to the macOS and Windows implementations.

**Comment by lemarier** [comment]
Hi buddy,

I need to make some refactoring to the menu for the accelerators. 
Please hold a bit I'll try to push changes ~ Monday, but you can work to get the native call to `winapi` and `cocoa` to works

Thanks!

**Comment by fnune** [comment]
Hey! Wondering if I'm safe to rebase and continue working now?

**Comment by lemarier** [comment]
I didnt finished but you can take a look at https://github.com/tauri-apps/tao/pull/77

Edit: I’ll suggest to wait a bit as a complete refactoring is in progress for a cleaner codebase

**Comment by lemarier** [comment]
But you can do the linux part (of the PR #77 ) if you want to help!

**Comment by lemarier** [comment]
Closing in favor of https://github.com/tauri-apps/tao/pull/77

Thanks for your time tho we really appreciate it.

If you think there is something we should modify or expose in  #77 feel free to create a new PR!

**Comment by fnune** [comment]
Thank you so much!

I'm sorry I couldn't continue with this on time.

**Comment by wusyong** [comment]
@fnune Don't be sorry! This is an open-source project and it requires voluntary. It's okay that thing isn't delivered sometimes.

**Pull request closed without merging**
