### PR TITLE
On macOS, add `WindowExtMacOS::reset_cursor_rect`

### PR DESCRIPTION
**Pull request by wusyong**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by amrbashir — COMMENTED** [review]
I am not sure if this fix will be accepted upstream, how would this be used in WRY btw?

**Comment by wusyong** [comment]
@amrbashir wry will call `window.reset_cursor_rect(false)` internally when creating webview.
I don't know if upstream would accept either. But this is the only I can think of without replacing TaoView.
Replacing TaoView will lose lost of WindowEvent including resize event.

**Comment by amrbashir** [comment]
calling `window.reset_cursor_rect(false)` will effectively disable `window.set_cursor_icon()`?

**Comment by wusyong** [comment]
Yes, this is `resetCursorRects:` is used for loading custom cursor in TaoView.
Wen `set_cursor_icon` is called, it will invoke `invalidateCursorRectsForView:` which will trigger `resetCursorRects:`

**Comment by amrbashir** [comment]
I don't think users will appreciate disabling the `window.set_cursor_icon`, maybe `window.set_cursor_icon` could be changed to take `Option<CusrsorIcon>` and calling it with `None` variant will make tao/winit fallback to the system behavior.

**Comment by wusyong** [comment]
Closed this in favor of #614

**Pull request closed without merging**
