### PR TITLE
On Windows, not transparent and not decorated windows have shadows.

### LINKED ISSUE #157: feat: `with_has_shadow`, `has_shadow` and `set_has_shadow`
**Is your feature request related to a problem? Please describe.**
When using `decorations: false` the app removes not only the topbar & border, but also the shadow. 

**Describe the solution you'd like**
I would like to see the shadow separated into it's own config property. So you could e.g. do:
```
"windows": [
  {
    "shadow": true,
    "decorations": false
  }
]
```
Which would result in a window without the top bar, without borders but *with* the OS shadow.

**Describe alternatives you've considered**
I tried building this in my app, but this comes with a lot of edge cases. You can't click through the shadow, you have to dynamically change the spacing/shadow when you are full screen, etc.

**Additional context**
This was experienced on Windows, I have not tested behavior on other OS'.

### PR DESCRIPTION
**Pull request by blemelin**
### What kind of change does this PR introduce?

- [X] Bugfix
- [X] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [X] No

### Checklist
- [X] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary

### Other information

Fixes #157 for Windows. Non-decorated non-transparent windows now have shadows.

### CODE REVIEW

**Comment by blemelin** [comment]
Since this changes the behaviour when creating a window on windows, does this require a change file ?

**Comment by FabianLars** [comment]
> Since this changes the behaviour when creating a window on windows, does this require a change file ?

Yes, but don't expect to see this merged anytime soon. I think we don't add new APIs (unless absolutely needed) until after tauri v1 is released (I may be wrong about that since i'm not a wry/tao maintainer).
Also there's https://github.com/tauri-apps/window-shadows because of that.

Furthermore this doesn't really fix #157 since that one is about an API to set it. Your PR just always enables it, which is most likely not what's wanted? (think of overlay-like apps for example)

**Comment by blemelin** [comment]
> Furthermore this doesn't really fix #157 since that one is about an API to set it. Your PR just always enables it, which is most likely not what's wanted? (think of overlay-like apps for example)

Oh right. Understood.

> I think we don't add new APIs (unless absolutely needed).

Then, should I just document how to implement this feature and close this PR ?

**Comment by amrbashir** [comment]
Thanks but the `window-shadows` crate can be used with `tao` directly or `tauri` or `winit`.

I think we will keep the shadows in its separate crate instead of directly in `tao` and `tauri` v2 can depend on it and provide its option.

**Pull request closed without merging**
