### PR TITLE
feat: switch android_fn! to a proc_macro

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

This is rewrite was due to happen soon and it allows us to:
1. handle `_` in package name and escape it properly, instead of relying on users to pass it escaped.
2. support variadic arguments to functions (encountered while implementing https://github.com/tauri-apps/wry/issues/804)

### CODE REVIEW

**Review by wusyong — CHANGES_REQUESTED** [review]
LGTM, but you should add doc on those macro if we want to expose this.
And also add tao-macro to workspace and our CI config

**Comment by wusyong** [comment]
Or we could make this into separate repo and crate then.

**Comment by amrbashir** [comment]
> LGTM, but you should add doc on those macro if we want to expose this.
> And also add tao-macro to workspace and our CI config

will do, I was just looking for a first review for the macro code.

> Or we could make this into separate repo and crate then.

I'd rather keep this in the repo.

**Comment by wusyong** [comment]
> I'd rather keep this in the repo.

Alright! We keep int this repo then. I'm not concerned about the implementation since it's fairly short but I treat proc macro as a different DSL. A comprehensive documentation is required.

**Review by wusyong — APPROVED** [review]

**Pull request merged**
