### PR TITLE
fix(windows): fix aero-snap and resizing of borderless window, fixes #103 #104

### LINKED ISSUE #103: Aero-snap doesn't work for a window without decorations on Windows

### LINKED ISSUE #104: Allow resizing of a window without a decorations on Windows

### PR DESCRIPTION
**Pull request by amrbashir**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by amrbashir** [comment]
If you have trouble seeing the borderless window, try changing this line 
https://github.com/tauri-apps/tao/blob/cbd4cdbeb8a36bf1dbc64ce2e10a55fe3ce6b5b4/src/platform_impl/windows/window.rs#L1008
 to `hbrBackground: winuser::COLOR_WINDOW as _,`

**Comment by Blakeinstein** [comment]
Any plans for implementing this as well? https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmextendframeintoclientarea

**Comment by amrbashir** [comment]
@Blakeinstein what's the use case for it? does the window not have shadows by default ?

**Comment by amrbashir** [comment]
@Blakeinstein just pushed a commit with shadows, test it and let me know what you think.

**Comment by Blakeinstein** [comment]
> 
> @Blakeinstein just pushed a commit with shadows, test it and let me know what you think.

Oh yea sorry I wasn't available yesterday. It works great! 

So does the resize.

Can you test one thing for me? Resizing a frameless window had a delay on sending the resize event to the webview on boscop/webview. This results in white gaps being visible for a few seconds. Can you try this with tauri?

**Comment by Blakeinstein** [comment]
I don't know about cross-compatibility. But later down the road can we expose the margins as an api? 

example: https://docs.microsoft.com/en-us/windows/win32/dwm/blur-ovw

**Comment by amrbashir** [comment]
I have plans to: 
1. Provide API to set the shadows if possible on all platforms
2. Provide Blur/Acrylic/Vibrancy API

but all of that is out of this PR scope.

**Comment by Blakeinstein** [comment]
> 
> 
> I have plans to:
> 
>     1. Provide API to set the shadows if possible on all platforms
> 
>     2. Provide Blur/Acrylic/Vibrancy API
>        but all of that is out of this PR scope.

That sounds awesome! Thanks again!

**Review by lemarier — APPROVED** [review]

**Pull request merged**
