### PR TITLE
Fix CI and copy wry structure

### PR DESCRIPTION
**Pull request by lemarier**

### CODE REVIEW

**Review by nothingismagick — CHANGES_REQUESTED** [review]
Great start, but we need the license headers too.

**Comment by lemarier** [comment]
> Great start, but we need the license headers too.

Sweet! Just need to kick the CI so we can get started adding / fixing right now. 

License and other stuff maybe you can do it in another PR ?

**Comment by lemarier** [comment]
> Great start, but we need the license headers too.

Also, I'm not sure what to do for covector, maybe @jbolda can help?

**Review by jbolda — APPROVED** [review]
covector setup looks good to me 👍

**Comment by nothingismagick** [comment]
ok, i will do the license stuff in another PR after we merge this one

**Pull request merged**
