### PR TITLE
Implement standalone webview ndk

### PR DESCRIPTION
**Pull request by wusyong**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by wusyong** [comment]
This PR will rewrite whole android stack.
The benefit from it is whole workflow on android will be just like others.
The downside is I need to write many webview code into tao since they are under the event loop.
@lucasfernog @amrbashir Do you have any opinion on this?
This is like we alter to gtk stack on Linux. I change the implementation on Android to be more webview specific.

**Comment by amrbashir** [comment]
The work you've done is remarkable but given our decision to move back to use winit, I don't know how will this fit into that.

**Comment by wusyong** [comment]
Yeah that's my concern too.
But we still need this one way or another. winit's android port is pure NDK.
We can't even define any class in that way, and this is hard requirement to implement IPC.

I think the reasonable choice would be android and linux port in tao will end up remain, and we maintain these ourselves. For the rest platforms, we will re-export from winit.
Does this match what you plan on moving back to winit?

**Comment by amrbashir** [comment]
yeah that sounds about right. 

I just thought we were gonna create a `winit_gtk` crate and have it under `rust-windowing` umbrella since the winit team offered to do so but I guess keeping gtk and android-webview in tao and reexport winit on other platforms is the optimal choice.

**Comment by wusyong** [comment]
Oh right, we can still propose `winit_gtk`. But that might not be the case on Android. Our implementation will be very webview specific.
On maintenance side, it contains around ~2000 LOC. It's fairly maintainable IMHO.

**Review by lucasfernog — DISMISSED** [review]

**Review by amrbashir — DISMISSED** [review]
We can decide later whether we keep gtk and android webview glue code under `tao` or make `winit_gtk` and `tao` would re-export it. For now, this PR is fine. Great work as always.

**Pull request merged**
