### PR TITLE
feat(linux): implement `Window::set_cursor_position`

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [X] No

### Checklist
- [X] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by amrbashir** [comment]
I don't even know if this works (don't have access to a PC rn), so test and confirm before merge.

**Comment by lucasfernog** [comment]
Don't tell me you're developing on your Android phone like that dude :joy:

**Comment by lucasfernog** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaand it works! You're the best mobile developer in the world!

**Review by lucasfernog — APPROVED** [review]

**Comment by amrbashir** [comment]
> Don't tell me you're developing on your Android phone like that dude 

termux and neovim magic 😉

Anyways, thanks for the quick test and for the kind words.

**Pull request merged**
