### PR TITLE
refactor: menus

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [X] Yes,
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix #___, #___`)
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary

#### Goals of this PR:
- make it cheap to clone menus and menu items
- introduce one `Menu` type that can work for menu bars and popup menus, so we can do something like this
	```rs
	let menu_bar = Menu::new();
	let file_menu = Menu::with_title("File");
	let edit_menu = Menu::with_title("Edit");
	menu_bar.add_submenu(&file_menu);
	menu_bar.add_submenu(&edit_menu);
	
	// proceed to add menu items to each menu
	// then we can use the same menu in different ways
	
	// 1. window menu (Windows and Linux)  
	window.set_menu(Some(menu_bar)); 

	// 2. app menubar (macOS only) see below!
	event_loop.set_menu(Some(menu_bar));
	
	// 3. system tray menu (Windows, Linux, and macOS)
	SystemTrayBuilder::new(tray_icon, Some(menu_bar));
	system_tray.set_menu(Some(menu_bar));
	
	// 4. window context menu, eg, right click (Windows, Linux, and macOS)
	window.showContextMenu(&menu_bar , 100, 200); // this method will be introduced later after tauri v1
	```
- menubar on macOS is not bound to the window, it is app-wide so we should have something like this
	```rs
	let menu = Menu::new();
	event_loop.set_menu(&menu);
	```
#### Platforms implemented:
- [X] Windows
- [ ] Linux
- [ ] macOS

### CODE REVIEW

**Comment by amrbashir** [comment]
I think Windows is done now with a single bug that is not super important. I will move on to Linux next.

**Comment by xuchaoqian** [comment]
Great job! 
Looking forward to this API: window.showContextMenu. Without this API, it needs a lot of code to creating a usable context menu in JS&CSS.

**Comment by FabianLars** [comment]
As [requested](https://github.com/tauri-apps/tauri/issues/3642#issuecomment-1062075058) the reminder for `ÄÖÜ` characters, quote:
> What it doesn't fix tho, is ÄÖÜ. These chars work fine if you create the item with it, but not in the command above. Any idea if that's auto fixed by that PR too?

That said i couldn't repro that in tao@dev directly, only in tauri with the example tauri command posted there.

**Comment by amrbashir** [comment]
Linux isn't playing nicely with this what I did on Windows. I need to rethink this refactor thoroughly from scratch. I will close the PR for now and will revisit it later in tauri@v2.

**Pull request closed without merging**
