### PR TITLE
Fix: Event can't be cloned #484

### PR DESCRIPTION
**Pull request by ghostnumber7**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
Bug description in [issue 484](https://github.com/tauri-apps/tao/issues/484)

### CODE REVIEW

**Review by amrbashir — APPROVED** [review]
does this seem okay with you @wusyong

**Comment by wusyong** [comment]
Fine by me, but need to aware that winit is still `'static`

**Comment by amrbashir** [comment]
right!
@ghostnumber7 do you really need to clone? can't you just use `&event` or `&mut event`? because there is some event variants that could be modified (`WindowEvent::ScaleFactorChanged` iirc)so you'd better take a reference

**Comment by ghostnumber7** [comment]
> right! @ghostnumber7 do you really need to clone? can't you just use `&event` or `&mut event`? because there is some event variants that could be modified (`WindowEvent::ScaleFactorChanged` iirc)so you'd better take a reference

I was trying to do  `event.map_nonuser_event::<SomeOtherUserEventThing>()` to be able to send non user events somewhere else to be handled by a plugin or alike. As in, I don't care to handle menu events for example, but there is something else that needs to, and don't want to map every single possible event one by one. The clone thing is an example to reproduce easily, but the real problem is that I can do nothing to send the event to some other place, except one by one mapping. Felt like that was the whole idea behind `map_nonuser_event` method and could need a fix :)

**Comment by amrbashir** [comment]
does this work for you?

```rs
fn handle_events<T>(event: &mut Event<T>) {};
```
then in your eventloop run callback
```rs
let mut event = event.map_nonuser_event::<SomeOtherUserEventThing>();

// handle the events somewhere elese
handle_events(&mut event);

// rest of the run callback
match event {
}

```

**Comment by amrbashir** [comment]
also have you looked at `Event::to_static` then you can call `clone` on it.

**Comment by ghostnumber7** [comment]
> ```rust
> map_nonuser_event
> ```

If I try that I get an error 
```rust
event_loop.run(move |window_event, event_loop, control_flow| {
        *control_flow = ControlFlow::Wait;

        let mut event = window_event.to_static().unwrap().map_nonuser_event::<()>();
        // same happens with let mut event = window_event.map_nonuser_event::<()>();
        println!("moved {:?}", event);

        match window_event {
            Event::NewEvents(StartCause::Init) => { ...
```

```shell
error[E0382]: use of moved value
   --> packages/desktop/src/lib.rs:215:24
    |
115 |     event_loop.run(move |window_event, event_loop, control_flow| {
    |                          ------------ move occurs because `window_event` has type `wry::application::event::Event<'_, UserWindowEvent>`, which does not implement the `Copy` trait
...
118 |         let mut event = window_event.to_static().unwrap().map_nonuser_event::<()>();
    |                                      ----------- `window_event` moved due to this method call
...
215 |                 event, window_id, ..
    |                        ^^^^^^^^^ value used here after move

```

I think the issue is that inside the closure for `event_loop.run` it can't be static at all if I want to use it twice.

**Comment by ghostnumber7** [comment]
Note that "rest of the code" uses the original event, not the casted one, so it explodes when it gets moved

**Comment by amrbashir** [comment]
if you want to be able to handle the original event then you need to either:

- handle it before calling `map_nonuser_event`
```rs
	  event_loop.run(move |event, event_loop, control_flow| {
	          *control_flow = ControlFlow::Wait;
	          
	          match event {
	              ...
	          }
	  
	          let mut nonuser_event = event.map_nonuser_event::<()>();
```
- or turn it into static then clone it and then call `map_nonuser_event`
```rs
	    event_loop.run(move |event, event_loop, control_flow| {
		            *control_flow = ControlFlow::Wait;
		            
		            let mut event = event.to_static().unwrap();
		            let nonuser_events = event.clone().map_nonuser_event::<()>();
		            
		            match event {
		              ...
		    
```

**Comment by ghostnumber7** [comment]
> if you want to be able to handle the original event then you need to either:
> 
> * handle it before calling `map_nonuser_event`
> 
> ```rust
> 	  event_loop.run(move |event, event_loop, control_flow| {
> 	          *control_flow = ControlFlow::Wait;
> 	          
> 	          match event {
> 	              ...
> 	          }
> 	  
> 	          let mut nonuser_event = event.map_nonuser_event::<()>();
> ```
> 
> * or turn it into static then clone it and then call `map_nonuser_event`
> 
> ```rust
> 	    event_loop.run(move |event, event_loop, control_flow| {
> 		            *control_flow = ControlFlow::Wait;
> 		            
> 		            let mut event = event.to_static().unwrap();
> 		            let nonuser_events = event.clone().map_nonuser_event::<()>();
> 		            
> 		            match event {
> 		              ...
> 		    
> ```

yep, that works.

**Comment by amrbashir** [comment]
We are trying to minimize the differences between tao and winit so the transition back to winit can be easier.

On that note, I am gonna close this and the relevant issue.

**Comment by ghostnumber7** [comment]
> We are trying to minimize the differences between tao and winit so the transition back to winit can be easier.
> 
> On that note, I am gonna close this and the relevant issue.

Thanks for the help :)

**Pull request closed without merging**
